### ISSUE TITLE
Dependency badges are broken

### ISSUE THREAD

**Issue by snuggs** [bahmutov/clean-console#18]
![capture d ecran 2016-11-06 a 11 35 49](https://cloud.githubusercontent.com/assets/38223/20039641/3a23ec8c-a415-11e6-858e-fe28928b5849.png)

**Comment by snuggs** [comment]
Weird ow they are back. I took care of the NPM one in https://github.com/bahmutov/clean-console/pull/17

![capture d ecran 2016-11-06 a 11 37 32](https://cloud.githubusercontent.com/assets/38223/20039654/7013aa1c-a415-11e6-8079-abc897a80aec.png)

**Comment by bahmutov** [comment]
Yeah, I have noticed that badges are sometimes broken on GitHub readmes, blame the internets!
